### ISSUE TITLE
System.getProperty("java.version") format in Java 9.

### ISSUE THREAD

**Issue by 5hubh4m** [Waikato/moa#118]
In Java 9, the `System.getProperty("java.version")` is simply the string `"9"`. Therefore the call `version.charAt(2)` throws exception.

`$ java -version`
`java version "9"`
`Java(TM) SE Runtime Environment (build 9+181)`
`Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)`

`$ java -cp moa.jar -javaagent:(pwd)/sizeofag-1.0.0.jar  moa.gui.GUI`
`java.lang.StringIndexOutOfBoundsException: String index out of range: 2`
`	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)`
`	at java.base/java.lang.String.charAt(String.java:704)`
`	at moa.DoTask.isJavaVersionOK(DoTask.java:60)`
`	at moa.gui.GUI.main(GUI.java:78)`

On macOS 10.13 with `brew cask install java`.

**Comment by abifet** [comment]
Thanks! We solved this issue in this commit:

https://github.com/Waikato/moa/commit/7265bb566face3d015d11246de1a97d572481283
