### ISSUE TITLE
Grid Search and Random Search in MOA?

### ISSUE THREAD

**Issue by yuhang-lin** [Waikato/moa#122]
Can anyone tell me whether grid search and random search are supported in MOA?

**Comment by hmgomes** [comment]
They are not.

**Comment by yuhang-lin** [comment]
Thank you. Do you have any advice to implement the random search? @hmgomes

**Comment by hmgomes** [comment]
No problem. You can extend one of the Task classes (take a look at EvaluatePrequentialCV), if you are looking for a specific algorithm to tune it will be easier as there is not a unified interface to setup the hyper-parameters.
