### ISSUE TITLE
plotes in MOA

### ISSUE THREAD

**Issue by Reyhane14** [Waikato/moa#136]
Hi,
I use Adaptive Hoeffding tree by  MOA in my research and I have some problem.  I will be wounder if help me.
I have some questions:
1. How can show number of active leaves  for instances by plot?
2.  Can show false positive or ROC metrics for evaluate model?
and is it possible to compare accuracy of an streaming method with other machine learning method like KNN (batch learning)?

Thanks

**Comment by hmgomes** [comment]
Hi there, 

1. check ```activeLeafNodeCount``` in [HoeffdingAdaptiveTree.java](https://github.com/Waikato/moa/blob/master/moa/src/main/java/moa/classifiers/trees/HoeffdingAdaptiveTree.java)
2. You can use AUC or other metrics available. It is possible to compare it against other machine learning methods, Knn is implemented in MOA as well.
