### ISSUE TITLE
Sparse ARFF not Supported

### ISSUE THREAD

**Issue by Humni** [Waikato/moa#139]
I was attempting to use a sparse ARFF as per the published specification, but it seems that they are not read correctly by the moa.streams.clustering.FileStream file reader. I discovered this when implementing a custom clustering outlier, I have provided the example ARFF files and the output I get from printing the instances below

**Sparse ARFF - This one doesn't work**
```
@RELATION navigationsequences 

@ATTRIBUTE "GET /~scottp/publish.html" NUMERIC
@ATTRIBUTE "GET /~lowey/kevin.gif" NUMERIC
@ATTRIBUTE "GET /~ladd/ostriches.html" NUMERIC
@ATTRIBUTE "GET /~lowey/" NUMERIC

@DATA
{0 1}
{2 1}
{0 1}
{3 1, 1 1}
```
**Sparse ARFF Output**
```
instance: [ ] 
instance: [ ] 
instance: [ ] 
instance: [ 0.00 ]
```

**Normal ARFF - This one works**
```
@RELATION navigationsequences 

@ATTRIBUTE "GET /~ladd/ostriches.html" NUMERIC
@ATTRIBUTE "GET /~scottp/publish.html" NUMERIC
@ATTRIBUTE "GET /~lowey/kevin.gif" NUMERIC
@ATTRIBUTE "GET /~lowey/" NUMERIC

@DATA
0, 1, 0, 0
1, 0, 0, 0
0, 1, 0, 0
0, 0, 1, 1
```
**Sparse ARFF Output**
```
instance: [ 0.00 1.00 0.00 ] 
instance: [ 1.00 0.00 0.00 ] 
instance: [ 0.00 1.00 0.00 ] 
instance: [ 0.00 0.00 1.00 ] 
```

**Comment by abifet** [comment]
Clustering in MOA only works with normalised dense instances.
