### ISSUE TITLE
Maven build error on pom.xml

### ISSUE THREAD

**Issue by Sun-Yuting** [Waikato/moa#151]
I am trying to build MOA from its source code, but I got an error in the pom.xml file in the top folder. The error is at the <parent> tab.
I Googled it. It seems that Sonatype OSS Parent poms is no longer available or may be not compatible with latest Maven and Java versions. I would very much like to know which java and Maven versions this project built on.

Thank you very much.

**Comment by fracpete** [comment]
Can you please post your Java and Maven version?

**Comment by Sun-Yuting** [comment]
Really sorry for the late response.
I think I know what the problem is. Dut to my company's network, Maven cannot connect to the host to download a parent POM(if I explain it right.) I need to use a proxy.
By the way, I use Java 11 and Maven 3.5.4.
And thank you so much for helping me here.

**Comment by fracpete** [comment]
No worries. If you're behind a proxy, you can define that in your $HOME/.m2/settings.xml file.

**Comment by fracpete** [comment]
Here is more information on configuring proxies in your settings.xml:
https://maven.apache.org/guides/mini/guide-proxies.html
