### ISSUE TITLE
How to implement Cramer's test in Java? - Cramer - 'ArrayStoreException'

### ISSUE THREAD

**Issue by betrw** [Waikato/moa#152]
Submitting the parameters to the method:

Cramer c = new Cramer();
c.cramerTest1(CR1, CR2);
pi.CremerTValue = ?

fails with the error 'ArrayStoreException' at the second line after passing the parameters.

I tried:

List<List<Double>>CR1 = new ArrayList<List<Double>>();
List<List<Double>>CR2 =  new ArrayList<List<Double>>();

CR1.add(First);
CR2.add(Second);

--or--

List<List<Double>>CR1 = Arrays.asList(First);
List<List<Double>>CR2 = Arrays.asList(Second);

Both declarations failed.

First and Second are both of the type ArrayList<Double> with a size of 177 items.
CR1 and CR2 have one item that contain 177 values.

How can I implement the two sample Cramer-Mises T test?

**Comment by betrw** [comment]
I guess the two samples Cramer test is the Anderson-Darling-Test?

**Comment by abifet** [comment]
@pmgj: can you help on this? Thanks!

**Comment by pmgj** [comment]
Hi,

  This cramer test works comparing the attribute values of a List of Instance elements. An example that can read values from ARFF files is:

`
        List<Instance> x = Cramer.fileToInstances("test1-x.arff");
        List<Instance> y = Cramer.fileToInstances("test1-y.arff");

        Cramer c = new Cramer();
        Cramer.CramerTest ct = c.cramerTest(x, y);
        System.out.println("p Value.: " + ct.pValue);
        System.out.println("Critical value: " + ct.critValue);
        System.out.println("Statistic: " + ct.statistic);
`
The CramerTest is only used inside the class. I probably had to make it private. This Java implementation was based on the Cramer test source code available in the R statistic tool.

**Comment by betrw** [comment]
Thanks a lot.
