### ISSUE TITLE
rxjava observable to stream

### ISSUE THREAD

**Issue by mbehrisch** [Waikato/moa#161]
Hi,

I'm a bit stuck.... I have a range of conceptual, implementation and understanding questions. 

1. [EASY] Where can I find the latest _Javadoc_?
2. [A bit history] Why do I see the _mix_ between the yahoo/apache samoa, moa classes, and weka (e.g., InstanceHeader)??
3) [Impl] Little bit of context: I'm receiving data through a socket.io connection and distribute it directly through a Java rxJava Observable implementation ==  _my stream_. As long as I define the InstanceHeader for bootstrapping the algorithms e.g., `myOutlierDetector.setModelContext(stream.getHeader());` and use (weka) Instances for the algorithm input I should be fine, right?

Thanks

**Comment by abifet** [comment]
1. You can find the javadoc inside the last release.
2. MOA uses samoa instances now, instead of weka instances as before.
3. In MOA you need to use samoa instances, not weka instances.
