### ISSUE TITLE
Reading ARFF file when using MOA’s API with Scala

### ISSUE THREAD

**Issue by Reyhanea** [Waikato/moa#165]
I will be very grateful if you can help me out how the data with .arff format could be used to the Adaptive Hoeffding tree so that it can get the model accuracy using the prequential method. In the code provided in the "https://moa.cms.waikato.ac.nz/using-moas-api-with-scala/" link, RandomRBFGenerator is utilized as the input data, but to give the .arff formatted data, it is not possible to use the functions used in this code, such as the stream.prepareForUse (). 

Is it possible to guide me what functions should be used to give .arff format data as input to the Hoeffding tree model in this code?

**Comment by fracpete** [comment]
You can use the [moa.streams.ArffFileStream](https://github.com/Waikato/moa/blob/master/moa/src/main/java/moa/streams/ArffFileStream.java) stream generator for that.
