### ISSUE TITLE
Instance documentation

### ISSUE THREAD

**Issue by abdelrahman-t** [Waikato/moa#178]
Is there any documentation on how to convert vectors into Instances, I see that all clusteres expect "Instance" instances not array of numbers, So I was wondering how to generate the header also what is classIndex, classValue. in my case the ground truth clusters are unknown.

provided that I have **some vectors** (Not one of the supported stream generators) without ground truth clusters, Could you provide an example for how to use any of the available clusterers?

Thanks

**Comment by hmgomes** [comment]
Regarding your first question about creating Instances. You can look at SRP [prepareRandomSubspaceInstance(...)](https://github.com/Waikato/moa/blob/5bf4fa24b9e6962a70fdad41c3850214269f5428/moa/src/main/java/moa/classifiers/meta/StreamingRandomPatches.java#L465) which creates a new instance from an existing Instance.
