### ISSUE TITLE
trying to add new clusterers

### ISSUE THREAD

**Issue by ElemenT5ven** [Waikato/moa#186]
Hello, 

I'm trying to test if i can add a new clusterers algorithm to MOA but have some issues.

After I have compiled the clusterers with this command in the "lib" directory of the moa release 2019:
javac -cp moa.jar MyClusterer.java

It say, in the Moa Manual, to create a moa directory and classifiers directory inside for the creation of new classifiers in manual, so i did the same for clusterers and pasted my MyClusterer.class in a clusterers directory in moa. The moa directory I created is in the lib directory, is it right? Because when i lunch moa.sh in bin directory, I can't find my MyClusterer in the GUI.

What did i do wrong? maybe it's not the right directory to paste my MyClusterer.class? But where?

Thanks,

**Comment by fracpete** [comment]
Using straight javac is probably not the best way of developing, but it should (in theory) work.
Your Java class must use `moa.clusterers` as package and the class itself must be derived from the abstract superclass `moa.clusterers.AbstractClusterer`.
In the future, please use the appropriate mailing list for your questions:
https://moa.cms.waikato.ac.nz/people/contact/
