### ISSUE TITLE
EFDT ignores maxByteSizeOption

### ISSUE THREAD

**Issue by hansblafoo** [Waikato/moa#202]
Hi there,

I want to limit the size of the growing EFDT, but its maxByteSizeOption is useless. The problem is that the calculation of the tree size (estimateModelByteSizes()) is only triggered by a method of the nested static inner class VFDT (trainOnInstanceImpl()). However, the VFDT, which is a subclass of EFDT, cannot be instantiated - not even with reflection as there is no constructor.

Best regards

**Comment by abifet** [comment]
You're right. This is something that needs to be fixed.
