### ISSUE TITLE
MOA does not launch

### ISSUE THREAD

**Issue by gintriago12** [Waikato/moa#203]
Hi all,

I have been trying to run MOA after installation in three machines MacBookPro Mojave 10.14.5, iMac Mojave 10.14.6, and Windows 10 in virtual machine. I have tried 3 releases: 2019.04, 2014.11, 2012.08. Basically, I doubled click moa.jar file, but nothing happens. Please, your help.

Best,

**Comment by fracpete** [comment]
After downloading [moa-release-2019.05.0-bin.zip](https://github.com/Waikato/moa/releases/download/2019.05.0/moa-release-2019.05.0-bin.zip) and unzipping the archive, you need to start MOA via the *bin/moa-for-mac.command* script.
Double-clicking on the jar itself won't do anything, that only applied to very old MOA releases that came as a single jar file.

**Comment by gintriago12** [comment]
Hi Pete,

When I do that I get this message:

<img width="524" alt="imagen" src="https://user-images.githubusercontent.com/17325256/78094664-ebae3d80-7389-11ea-80cf-48738fa24578.png">

Best,

**Comment by fracpete** [comment]
Unfortunately, I'm not a Mac user (I'm on Linux Mint).
Maybe your Java version is a problem? Are you using Java 8?

**Comment by gintriago12** [comment]
I have read that it may be related to a permission problem. But, besides that, I dont know.

**Comment by gintriago12** [comment]
I installed latest version of Java, and run moa-for-mac from the terminal.

<img width="567" alt="imagen" src="https://user-images.githubusercontent.com/17325256/78096469-8741ad00-738e-11ea-86e5-0efccfb36c8a.png">

But, still have that error.

**Comment by fracpete** [comment]
Have you checked the permissions on the extracted archive folder?
Please try it with Java 8, not later versions.

**Comment by gintriago12** [comment]
I moved the unzipped moa folder to the Desktop. Then, the issue was solved. It seems it had an issue with my google drive folder. Thanks Pete.

**Comment by fracpete** [comment]
Good to know!
