### ISSUE TITLE
Time measurement for AdaptiveRandomForest in parallel mode

### ISSUE THREAD

**Issue by Jwata** [Waikato/moa#228]
`DoTask` measures CPU time of `TaskThread`.
https://github.com/Waikato/moa/blob/f8b4d485253ff4917240435b388d0d26fc7b325a/moa/src/main/java/moa/DoTask.java#L225

Since I'm not expert at Java, I may be wrong.  
But when running AdaptiveRandomForest learner with multi threads (= with `numberOfJobs` option), I suspect time spent on the AdaptiveRandomForest threads isn't included in the `TaskThread` time in `DoTask`.
https://github.com/Waikato/moa/blob/f8b4d485253ff4917240435b388d0d26fc7b325a/moa/src/main/java/moa/classifiers/meta/AdaptiveRandomForest.java#L160

Is my understanding correct?
If so, is it ok to use wall clock time for measuring ARF runtime?

**Comment by hmgomes** [comment]
Hi @Jwata 
Your understanding is correct. You should measure the wall clock time in this case.

**Comment by Jwata** [comment]
@hmgomes 
Thank you for your confirmation. Will measure wall clock time.
