### ISSUE TITLE
Cannot find specific algorithms which are on Github but not on application

### ISSUE THREAD

**Issue by GilbertFan** [Waikato/moa#246]
Hi there
It may be a silly question. 
I am new to MOA and want to use it in my research. I can clearly see some algorithms' implementations on the Github repo, such as AUE2, LearnNSE. However, I cannot find it anywhere when I launch the application. Could someone tells me how I can use these algorithms? 
Any advice would be appreciated!

Cheers

**Comment by abifet** [comment]
You need to use the standard mode:
https://moa.cms.waikato.ac.nz/new-lite-mode-for-beginners/

Cheers, Albert

**Comment by GilbertFan** [comment]
Thanks!
