### ISSUE TITLE
Tutorial 2 example code compilation error

### ISSUE THREAD

**Issue by ddugovic** [Waikato/moa#42]
Your [example code](http://moa.cms.waikato.ac.nz/using-moas-api-with-scala/) fails to compile.  I first compiled the contents of `moa-2015.11-sources.jar`, then attempted the following:

> $ javac -cp "moa-release-2015.11/sources/bin:moa-release-2015.11/lib/*" Experiment.java 
> Experiment.java:27: error: incompatible types: InstanceExample cannot be converted to Instance
>                         Instance trainInst = stream.nextInstance();
>                                                                 ^
> Experiment.java:29: error: incompatible types: weka.core.Instance cannot be converted to com.yahoo.labs.samoa.instances.Instance
>                                 if (learner.correctlyClassifies(trainInst)){
>                                                                 ^
> Experiment.java:34: error: no suitable method found for trainOnInstance(weka.core.Instance)
>                         learner.trainOnInstance(trainInst);
>                                ^
>     method Learner.trainOnInstance(Example<com.yahoo.labs.samoa.instances.Instance>) is not applicable
>       (argument mismatch; weka.core.Instance cannot be converted to Example<com.yahoo.labs.samoa.instances.Instance>)
>     method Classifier.trainOnInstance(com.yahoo.labs.samoa.instances.Instance) is not applicable
>       (argument mismatch; weka.core.Instance cannot be converted to com.yahoo.labs.samoa.instances.Instance)
> Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
> 3 errors

**Comment by abifet** [comment]
Solved! We changed the import of weka Instance to samoa Instance.

**Comment by janardanMaurya** [comment]
this is the code that i am using for ADWIN 
//import com.yahoo.labs.samoa.instances.WekaToSamoaInstanceConverter;

import moa.classifiers.Classifier;
import moa.classifiers.bayes.NaiveBayes;
import moa.classifiers.core.driftdetection.ADWIN;
import moa.streams.ArffFileStream;
import weka.core.Instance;
import moa.core.InstanceExample;
import com.yahoo.labs.samoa.instances.SamoaToWekaInstanceConverter;

public class TestADWIN {

    public static void main(String[] args) {
        ArffFileStream stream = new ArffFileStream("F:/Phd Research Work/3rd sem/implementation/DataSet/sea.arff", -1);
        stream.prepareForUse();

        Classifier learner = new NaiveBayes();
        learner.setModelContext(stream.getHeader());
        learner.prepareForUse();


        ADWIN drift1 = new ADWIN();
        int numberSamplesCorrect = 0;
        int numberSamples = 0;
        int numberOfChanges = 0;

        while (stream.hasMoreInstances()) {
        	
       // WekaToSamoaInstanceConverterconv = new WekaToSamoaInstanceConverter();
      //  Instances data = conv.samoaInstances(stream);
        	
       // 	Instance trainInst=stream.nextInstance();
           Instance trainInst = (Instance) stream.nextInstance();
            learner.trainOnInstance((com.yahoo.labs.samoa.instances.Instance) trainInst);
            if (learner.correctlyClassifies((com.yahoo.labs.samoa.instances.Instance) trainInst)) {
                drift1.setInput(0);
                numberSamplesCorrect++;

            } else {
                drift1.setInput(1);
            }

            if (drift1.getChange()) {
                learner.resetLearning();
                System.out.println("point of change = " + numberSamples);
                numberOfChanges++;
            }
            numberSamples++;
        }
        System.out.println("Changes detected: " + numberOfChanges);
    }// end main
}// end class

But Showing this error: 
 Exception in thread "main" java.lang.ClassCastException: moa.core.InstanceExample cannot be cast to weka.core.Instance 	at TestADWIN.main(TestADWIN.java:33)

**Comment by abifet** [comment]
Please, can you try with the recent version of MOA, MOA 2017.06?

Thanks, Albert
