### ISSUE TITLE
Issue with WriteStreamToARFFFile

### ISSUE THREAD

**Issue by jaycwb** [Waikato/moa#43]
Dear all,

WriteStreamToARFFFile outputs categorical variables incorrectly.
It basically outputs the toString() method of instances, and no conversion between the integer that represents the index of the value to the actual string value is performed.
I could send this as a pull request, but I am unsure if the best solution is to make this correction at the toString method or at the WriteStreamToARFFFile manually.

Cheers,

Jean

**Comment by abifet** [comment]
The best solution is to modify toString() in InstanceImpl.

Cheers, Albert

**Comment by jaycwb** [comment]
Good. Will make a pull request tomorrow.

Jean
