### ISSUE TITLE
Problem with Fork

### ISSUE THREAD

**Issue by jaycwb** [Waikato/moa#44]
Hi all,

Just forked the current version available, builded and unit tested and everything was fine.
When opening the GUI and clicking "Configure", that's what I get:

------------------------------------------------------------------------
Building MOA: Massive Online Analysis 2016.03-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ moa ---
Exception in thread "AWT-EventQueue-0" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    moa/classifiers/trees/FIMTDD$FIMTDDSplitNode.learnFromInstance(Lweka/core/Instance;Lmoa/classifiers/trees/FIMTDD;Z)V @461: invokevirtual
  Reason:
    Type 'moa/classifiers/trees/FIMTDD' (current frame, stack[2]) is not assignable to 'moa/classifiers/trees/HoeffdingTree'
  Current Frame:
    bci: @461
    flags: { }
    locals: { 'moa/classifiers/trees/FIMTDD$FIMTDDSplitNode', 'weka/core/Instance', 'moa/classifiers/trees/FIMTDD', integer, integer, 'moa/classifiers/trees/HoeffdingTree$Node' }
    stack: { 'moa/classifiers/trees/FIMTDD$FIMTDDActiveLearningNode', 'weka/core/Instance', 'moa/classifiers/trees/FIMTDD' }
  Bytecode:

**Comment by abifet** [comment]
It seems that it needs weka.jar for 'weka/core/Instance'. Can you check if having weka.jar in the java classpath works fine? Thanks!

**Comment by jaycwb** [comment]
Hi Albert,

Indeed, with weka.jar in the classpath it works. But I don't follow, since weka is a dependency that is compiled together, isn't it?

Jean

**Comment by abifet** [comment]
I found the problem: moa has a maven dependency on meka that has a maven dependency with MOA 14.11. Having the two different versions of moa in the java classpath was causing the problem. I think that it should be solved now. Can you check? Thanks!

**Comment by jaycwb** [comment]
Perfect! Working fine now!
