### ISSUE TITLE
"java.lang.UnsupportedOperationException: Not yet implemented" in InstanceInformation.java

### ISSUE THREAD

**Issue by richard-moulton** [Waikato/moa#79]
Hello,

I am a Master's student in Computer Science at the University of Ottawa and I am trying to use the **moa.streams.clustering.FileStream** task in the Clustering tab of MOA as part of my thesis work. Specifically I am trying to read in the covtypeNorm.arff file that I have downloaded from the MOA website to experiment with the task's functionality before continuing on.

Unfortunately when I try to run this I get the following exception:

> Exception in thread "AWT-EventQueue-0"
> java.lang.UnsupportedOperationException: Not yet implemented
>     at com.yahoo.labs.samoa.instances.InstanceInformation.deleteAttributeAt (InstanceInformation.java:144)

A quick check of the relevant line of code shows that the **deleteAttributeAt** method in **InstanceInformation** is entirely the Exception thrower, leading me to conclude that this is not a problem with the data set but that this capability is not fully included. My two-part question is:

A) Is there an earlier version in which the **moa.streams.clustering.FileStream** task was functional? and
B) If not, is this something that I could work on and contribute to the project?

Thank you in advance,

Richard

**Comment by hmgomes** [comment]
Hi @richard-moulton, 

I believe this issue shall be solved soon, still, notice that there is a new version of MOA to be released next week, so it might take a while before someone look into this. If you end up solving it yourself, please let us know. 

Best Regards, 
Heitor

**Comment by hmgomes** [comment]
@richard-moulton 
Please take a look at this commit: 
https://github.com/Waikato/moa/commit/c1ceb94ed347be3420650e333b36be19147e3cff
If that solves your issue, it would be a good thing to close this issue. 

Best Regards, 
Heitor

**Comment by richard-moulton** [comment]
@hmgomes 
Thanks for pointing this out. I see that the **deleteAttribute** method in **InstanceInformation** is now implemented.

Running my task again (reading in the covtypeNorm.arff file) I was able to remove attributes both by specifying them in the **removeAttributes** option and by leaving the **keepNonNumericalAttr** option as FALSE.

This resolves the issue that I had flagged.
