### ISSUE TITLE
Integration to Weka from MOA broken? 

### ISSUE THREAD

**Issue by heoa** [Waikato/moa#94]
> Error: "Please add weka.jar to the classpath to use the Weka explorer."

I tried to do this 

`$ java -cp "/Applications/weka-3-8-1-oracle-jvm.app/Contents/Java/weka.jar" -jar /Applications/moa.jar 
`

but I am still getting the error so is the integration the WEKA from MOA broken?

I am testing things in macOS 10.11.6.

**Comment by abifet** [comment]
No, the integration with WEKA is working fine. You may have a problem with the classpath of your weka.jar file

**Comment by fracpete** [comment]
AFAIK you cannot mix -jar and -cp. Add both jars to the classpath using a single -cp (separated by ":") and use the appropriate class for starting MOA.
